name: Hello World
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]

env:
  GLOBAL_VAR: Hello
jobs:
  hello-world-save-artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/hello-world-javascript-action@main
      - run: echo "${{ env.GLOBAL_VAR }} ${{ github.repository_owner }}. We're under ${{ github.workspace }}"
      - run: echo ${{ vars.DUMMY_VAR }}
      - run: echo ${{ job.status }}
      - run: echo ${{ runner.os }}
      - run: echo ${{ secrets.DUMMY_SECRET }}
        if: ${{startsWith(github.repository_owner, '1pronix')}}
      - run: echo ${{ strategy.fail-fast }}
      - run: echo "*******************************************" > dummy.txt
      - name: Store dummy artifact
        uses: actions/upload-artifact@v3
        with:
          name: dummy-artifact
          path: dummy.txt

  hello-world-download-artifact:
    needs: [hello-world-save-artifact]
    runs-on: ubuntu-latest
    steps:
      - run: echo "Trying to download an artifact"
      - name: Download
        uses: actions/download-artifact@v3
        with:
          name: dummy-artifact
      - run: cat dummy.txt


