name: Parent WF
on:
  push:
    branches:
      - main

jobs:
  call-another-wf:
    permissions:
      contents: read
    uses: ./.github/workflows/wf-B.yml
    with:
      homeDir: /home/ec2
    secrets:
      token: ${{ secrets.DUMMY_SECRET }}