name: Child WF
on:
  workflow_call:
    inputs:
      homeDir:
        required: true
        type: string
    secrets:
      token:
        required: true
    outputs:
      dummyout:
        description: 'Dummy output'
        value: ${{ jobs.actual-runner.outputs.output1 }}

jobs:
  actual-runner:
    runs-on: ubuntu-latest
    steps:
      - id: step1
        run: echo "first=dummy" >> $GITHUB_OUTPUT

      - run: |
          echo 'Home dir: ${{ inputs.homeDir }}, \
          token: ${{ secrets.token }}'

    outputs:
      output1: ${{ steps.step1.outputs.first }}