name: Child WF
on:
  workflow_call:
    inputs:
      homeDir:
        required: true
        type: string
    secrets:
      token:
        required: true

jobs:
  actual-runner:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 'Home dir: ${{ inputs.homeDir }}, \
          token: ${{ secrets.token }}'